export const POST_REQUEST = 'POST_REQUEST';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_ERROR = 'POST_ERROR';
export const GET_DATA_BY_ID_REQUEST = 'GET_DATA_BY_ID_REQUEST';
export const GET_DATA_BY_ID_SUCCESS = 'GET_DATA_BY_ID_SUCCESS';
export const GET_DATA_BY_ID_FAILURE = 'GET_DATA_BY_ID_FAILURE';
